# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Path(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, methods: List[str]=None):  # noqa: E501
        """ParseData - a model defined in Swagger

        :param url: The url of the path.  # noqa: E501
        :type url: string
        :param methods: The methods of this path.  # noqa: E501
        :type methods: List[str]
        """
        self.swagger_types = {
            'url': str,
            'methods': List[str]
        }

        self.attribute_map = {
            'url': 'url',
            'methods': 'methods'
        }

        self._url = url
        self._methods = methods

    @classmethod
    def from_dict(cls, dikt) -> 'Path':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Path of this Path.  # noqa: E501
        :rtype: Path
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Path.


        :return: The url of this Path.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ParseData.


        :param url: The info of this ParseData.
        :type url: object
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def methods(self) -> List[str]:
        """Gets the methods of this Path.


        :return: The methods of this Path.
        :rtype: List[str]
        """
        return self._methods

    @methods.setter
    def methods(self, methods: List[str]):
        """Sets the methods of this Path.


        :param methods: The methods of this Path.
        :type methods: List[str]
        """
        if methods is None:
            raise ValueError("Invalid value for `methods`, must not be `None`")  # noqa: E501

        self._methods = methods
